### ISSUE TITLE
get_server_status() breaks

### ISSUE THREAD

**Issue by Ligthert** [proelke/albion-api-client#2]
```
>>> client.get_server_status()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/albion_api_client/client.py", line 81, in get_server_status
    server=server)).json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

This is due to the string giving you 3 weird UTF characters before the JSON kicks in (followed by a \n after the JSON).

I ended up bypassing this by cleaning it up using: 
```
  myContent = str(r.text)
  myContent = str(myContent[3:]).strip()
```

**Comment by proelke** [comment]
This is fixed in version 0.1.2.
